# Production environment configuration
spring.profiles.active=production

# Logging for Production environment
logging.level.com.example.shoppingcart=WARN
logging.level.org.mybatis=WARN
logging.level.org.springframework.jdbc.core=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN

# Log file path for Production
logging.file.path=/var/log/shopping-cart-app

# Performance and security settings
server.error.include-stacktrace=never
server.error.include-message=never